// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qalegwgqtyleuaowvuje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhbGVnd2dxdHlsZXVhb3d2dWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2NzY1OTEsImV4cCI6MjA4NzI1MjU5MX0.rK1lOSW3I3pJqNdlL29wIfiFHROU0LJzlcWV8kin_Uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});